server:
  port: 8888

  so:
# 海康车牌摄像头
hk:
  sdk-path: /home/data/hk/so
  img-path: /home/data/img/
  plate-number:
    device-ip: 192.168.1.198
    username: admin
    password: password
    port: 8000
  camera:
    - device-ip: 192.168.1.191
      username: admin
      password: password
      port: 8000
    - device-ip: 192.168.1.192
      username: admin
      password: password
      port: 8000